# These are supported funding model platforms (replace with your usernames if desired)
buy_me_a_coffee: your-username
github: your-username
# patreon: your-username
# ko_fi: your-username
# open_collective: username
